import type { JournalSpreadDefinition, JournalSpreadPosition } from "@/app/diario/types";

function buildSequentialPositions(count: number, prefix: string, columns = count): JournalSpreadPosition[] {
  return Array.from({ length: count }, (_, index) => ({
    id: `${prefix}-${index + 1}`,
    name: `Carta ${index + 1}`,
    row: Math.floor(index / columns) + 1,
    column: (index % columns) + 1,
  }));
}

const monthNames = [
  "Enero",
  "Febrero",
  "Marzo",
  "Abril",
  "Mayo",
  "Junio",
  "Julio",
  "Agosto",
  "Septiembre",
  "Octubre",
  "Noviembre",
  "Diciembre",
];

export const JOURNAL_SPREADS: JournalSpreadDefinition[] = [
  {
    id: "three-cards",
    name: "3 cartas",
    description: "Pasado, presente y dirección inmediata.",
    cardCount: 3,
    mode: "fixed",
    positions: [
      { id: "three-1", name: "Pasado", row: 1, column: 1 },
      { id: "three-2", name: "Presente", row: 1, column: 2 },
      { id: "three-3", name: "Consejo", row: 1, column: 3 },
    ],
  },
  {
    id: "four-cards",
    name: "4 cartas",
    description: "Mapa base de contexto, reto, recurso y avance.",
    cardCount: 4,
    mode: "fixed",
    positions: [
      { id: "four-1", name: "Situación", row: 1, column: 1 },
      { id: "four-2", name: "Reto", row: 1, column: 2 },
      { id: "four-3", name: "Recurso", row: 2, column: 1 },
      { id: "four-4", name: "Dirección", row: 2, column: 2 },
    ],
  },
  {
    id: "five-cards",
    name: "5 cartas",
    description: "Panorama completo para lectura reflexiva.",
    cardCount: 5,
    mode: "fixed",
    positions: buildSequentialPositions(5, "five", 5),
  },
  {
    id: "six-cards",
    name: "6 cartas",
    description: "Lectura expandida con dos hileras.",
    cardCount: 6,
    mode: "fixed",
    positions: buildSequentialPositions(6, "six", 3),
  },
  {
    id: "nine-cards",
    name: "9 cartas",
    description: "Cuadrícula 3x3 para ver patrones.",
    cardCount: 9,
    mode: "fixed",
    positions: buildSequentialPositions(9, "nine", 3),
  },
  {
    id: "celtic-cross",
    name: "Cruz Celta",
    description: "Profundiza el contexto y su evolución.",
    cardCount: 10,
    mode: "fixed",
    positions: [
      { id: "celtic-1", name: "Situación actual", row: 2, column: 2 },
      { id: "celtic-2", name: "Cruce / Reto", row: 2, column: 3 },
      { id: "celtic-3", name: "Raíz", row: 3, column: 2 },
      { id: "celtic-4", name: "Pasado", row: 2, column: 1 },
      { id: "celtic-5", name: "Meta consciente", row: 1, column: 2 },
      { id: "celtic-6", name: "Futuro próximo", row: 2, column: 4 },
      { id: "celtic-7", name: "Actitud", row: 1, column: 6 },
      { id: "celtic-8", name: "Entorno", row: 2, column: 6 },
      { id: "celtic-9", name: "Esperanzas y miedos", row: 3, column: 6 },
      { id: "celtic-10", name: "Resultado", row: 4, column: 6 },
    ],
  },
  {
    id: "pyramid",
    name: "Pirámide",
    description: "Base amplia con cierre en foco superior.",
    cardCount: 6,
    mode: "fixed",
    positions: [
      { id: "pyr-1", name: "Síntesis", row: 1, column: 2 },
      { id: "pyr-2", name: "Clave 1", row: 2, column: 1 },
      { id: "pyr-3", name: "Clave 2", row: 2, column: 2 },
      { id: "pyr-4", name: "Base 1", row: 3, column: 1 },
      { id: "pyr-5", name: "Base 2", row: 3, column: 2 },
      { id: "pyr-6", name: "Base 3", row: 3, column: 3 },
    ],
  },
  {
    id: "inverted-pyramid",
    name: "Pirámide invertida",
    description: "Visión amplia superior y aterrizaje final.",
    cardCount: 6,
    mode: "fixed",
    positions: [
      { id: "ipyr-1", name: "Panorama 1", row: 1, column: 1 },
      { id: "ipyr-2", name: "Panorama 2", row: 1, column: 2 },
      { id: "ipyr-3", name: "Panorama 3", row: 1, column: 3 },
      { id: "ipyr-4", name: "Filtro 1", row: 2, column: 1 },
      { id: "ipyr-5", name: "Filtro 2", row: 2, column: 2 },
      { id: "ipyr-6", name: "Conclusión", row: 3, column: 2 },
    ],
  },
  {
    id: "aspirational",
    name: "Aspiracional",
    description: "Diagnóstico de meta, bloqueo y puente de acción.",
    cardCount: 4,
    mode: "fixed",
    positions: [
      { id: "asp-1", name: "Estado actual", row: 1, column: 1 },
      { id: "asp-2", name: "Meta", row: 1, column: 2 },
      { id: "asp-3", name: "Bloqueo", row: 2, column: 1 },
      { id: "asp-4", name: "Puente", row: 2, column: 2 },
    ],
  },
  {
    id: "month",
    name: "Mes",
    description: "Seguimiento semanal del mes en curso.",
    cardCount: 4,
    mode: "fixed",
    positions: [
      { id: "month-1", name: "Semana 1", row: 1, column: 1 },
      { id: "month-2", name: "Semana 2", row: 1, column: 2 },
      { id: "month-3", name: "Semana 3", row: 1, column: 3 },
      { id: "month-4", name: "Semana 4", row: 1, column: 4 },
    ],
  },
  {
    id: "week",
    name: "Semana",
    description: "Energía diaria en ciclo de 7 días.",
    cardCount: 7,
    mode: "fixed",
    positions: [
      { id: "week-1", name: "Lunes", row: 1, column: 1 },
      { id: "week-2", name: "Martes", row: 1, column: 2 },
      { id: "week-3", name: "Miércoles", row: 1, column: 3 },
      { id: "week-4", name: "Jueves", row: 1, column: 4 },
      { id: "week-5", name: "Viernes", row: 1, column: 5 },
      { id: "week-6", name: "Sábado", row: 1, column: 6 },
      { id: "week-7", name: "Domingo", row: 1, column: 7 },
    ],
  },
  {
    id: "annual",
    name: "Anual",
    description: "Lectura de 12 meses para ciclos de aprendizaje.",
    cardCount: 12,
    mode: "fixed",
    positions: monthNames.map((month, index) => ({
      id: `annual-${index + 1}`,
      name: month,
      row: Math.floor(index / 4) + 1,
      column: (index % 4) + 1,
    })),
  },
  {
    id: "horseshoe",
    name: "Herradura",
    description: "Arco temporal para tendencia y resultado.",
    cardCount: 7,
    mode: "fixed",
    positions: [
      { id: "horse-1", name: "Pasado", row: 3, column: 1 },
      { id: "horse-2", name: "Transición", row: 2, column: 2 },
      { id: "horse-3", name: "Presente", row: 1, column: 3 },
      { id: "horse-4", name: "Centro", row: 1, column: 4 },
      { id: "horse-5", name: "Influencia", row: 1, column: 5 },
      { id: "horse-6", name: "Futuro cercano", row: 2, column: 6 },
      { id: "horse-7", name: "Resultado", row: 3, column: 7 },
    ],
  },
  {
    id: "tree-of-life",
    name: "Árbol de la Vida",
    description: "Mapa simbólico de 10 nodos.",
    cardCount: 10,
    mode: "fixed",
    positions: [
      { id: "tree-1", name: "Kether", row: 1, column: 3 },
      { id: "tree-2", name: "Chokmah", row: 2, column: 2 },
      { id: "tree-3", name: "Binah", row: 2, column: 4 },
      { id: "tree-4", name: "Chesed", row: 3, column: 1 },
      { id: "tree-5", name: "Geburah", row: 3, column: 3 },
      { id: "tree-6", name: "Tiphareth", row: 3, column: 5 },
      { id: "tree-7", name: "Netzach", row: 4, column: 2 },
      { id: "tree-8", name: "Hod", row: 4, column: 4 },
      { id: "tree-9", name: "Yesod", row: 5, column: 3 },
      { id: "tree-10", name: "Malkuth", row: 6, column: 3 },
    ],
  },
  {
    id: "free",
    name: "Libre",
    description: "Coloca y reordena cartas sin estructura fija.",
    cardCount: 0,
    mode: "free",
    positions: [],
  },
];
